version: "3.2"
services:
  unbound_amd64:
    image: eu.gcr.io/axial-radius-203218/hlab-dns:amd64
    networks:
      - dnet
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]

  unbound_armel:
    image: eu.gcr.io/axial-radius-203218/hlab-dns:arm6
    networks:
      - dnet
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]

networks:
  dnet:
    driver: overlay
