version: "3"
services:
  unbound:
    image: eu.gcr.io/axial-radius-203218/hlab-dns:x86
    networks:
      - dns_network
    ports:
      - "53:53/udp"
      - "53:53"
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints: [node.role == manager]

networks:
  dns_network:
    driver: overlay
