version: "3.2"
services:
  unbound_amd64:
    image: eu.gcr.io/axial-radius-203218/hlab-dns:amd64
    networks:
      - dnet
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]

  unbound_armel:
    image: eu.gcr.io/axial-radius-203218/hlab-dns:arm6
    networks:
      - dnet
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 10
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == worker]


networks:
  dnet:
    driver: overlay
